
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'p\x02(oM\xb9\xc6EF\x92\x15\xdf:F&\xee'
    
_lr_action_items = {'VAR_IDENTIFIER':([2,],[3,]),'INST_PROGRAM':([0,],[2,]),'SEMICOLON':([3,],[4,]),'$end':([1,4,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> INST_PROGRAM VAR_IDENTIFIER SEMICOLON','program',3,'p_program','/export/home/gustavo/git/Traductores/Entrega2/parser.py',12),
]
